import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../globals.css'

// Font
const inter = Inter({ subsets: ["latin"] });

// For SEO
export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Choose the auth strategies you need — passwords, email codes or links, OAuth and more.
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-dark-1`}>
            {/* Render the children which is going to be shown within this layout */}
            {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
